### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nicoladimauro** [Waikato/meka#12]
Dear all,
I am using the latest code from this repo and I am obtaining the following error on the attached CAL dataset (on which is well known that the exact match is zero).

Any idea?

NDM

[CAL500.f0.train.arff.gz](https://github.com/Waikato/meka/files/541385/CAL500.f0.train.arff.gz)
[CAL500.f0.test.arff.gz](https://github.com/Waikato/meka/files/541388/CAL500.f0.test.arff.gz)

```
ndm@ndm-ThinkPad-L420:~/Desktop/MANIAC$ /usr/bin/java -cp "./meka/lib/*" meka.classifiers.multilabel.BR -threshold PCut1 -t ./data/CAL500.f0.train.arff -T ./data/CAL500.f0.test.arff -verbosity 20 
java.lang.ArrayIndexOutOfBoundsException: 101
    at meka.core.Metrics.P_FmacroAvgL(Metrics.java:658)
    at meka.core.MLEvalUtils.getMLStats(MLEvalUtils.java:104)
    at meka.core.MLEvalUtils.getMLStats(MLEvalUtils.java:58)
    at meka.core.Result.getStats(Result.java:290)
    at meka.classifiers.multilabel.Evaluation.evaluateModel(Evaluation.java:334)
    at meka.classifiers.multilabel.Evaluation.runExperiment(Evaluation.java:220)
    at meka.classifiers.multilabel.ProblemTransformationMethod.runClassifier(ProblemTransformationMethod.java:172)
    at meka.classifiers.multilabel.ProblemTransformationMethod.evaluation(ProblemTransformationMethod.java:152)
    at meka.classifiers.multilabel.BR.main(BR.java:157)

```

**Comment by jmread** [comment]
Hi,

There seems to be a bug in the Metrics.P_FmacroAvgL function. This can be confirmed, by setting -verbosity 1 (which indicates to not calculate the F-measures), wherein it does not produce an exception, and furthermore gives exact match correctly 0, as you specify it should be.

We will look into this in more detail, thanks for raising this issue.

Cheers,

Jesse

**Comment by joergwicker** [comment]
Hi, 

a bit late reply: I am not able to reproduce this anymore. There was a bug in macro-averaging that I fixed a while ago: https://github.com/Waikato/meka/commit/f6f6f3d6da416b0dcb3db0d95baf8aa858ecaed6 that would have caused exactly this (line of code fits too). The current master branch should not have this issue anymore (and a quick test seems to be working). 

Cheers,

Joerg
