### ISSUE TITLE
Startup problems run.sh

### ISSUE THREAD

**Issue by ambitiousrookie** [Waikato/meka#51]
Hello,

I've just downloaded the Meka package and when trying to start run.sh i'm getting the following error:

Vlads-MacBook:~ vlad$ /Users/vlad/Downloads/meka-release-1.9.0/run.sh ; exit;\
Exception in thread "main" java.lang.NoClassDefFoundError: meka/gui/guichooser/GUIChooser\
Caused by: java.lang.ClassNotFoundException: meka.gui.guichooser.GUIChooser\
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)\
	at java.security.AccessController.doPrivileged(Native Method)\
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)\
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)\
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)\
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)\
logout\
Saving session...\
...copying shared history...\
...saving history...truncating history files...\
...completed.\
Deleting expired sessions...40 completed.\
\
[Process completed]\
}

Does anybody know what the problem might be?

**Comment by fracpete** [comment]
See reply on mailing list:
https://sourceforge.net/p/meka/mailman/meka-list/thread/1172206661.1632900.1536166767465%40mail.yahoo.com/#msg36408579
